### ISSUE TITLE
Client crashes on placing mod "pipes" on connection points

### ISSUE THREAD

**Issue by tali713** [NPException42/Dimensional-Pockets#70]
I have had consistent client crashes when placing pipes from inside a dimensional pocket.  I don't know whether this also affects SSP.  Editing my player data and rebooting Minecraft is laborious enough that I have only done minimal case testing.

I have tested only with thermal dynamics item ducts and extra utilities pipes, currently using 10.4.  Hoppers work totally fine, otherwise I get highly similar crashes to the one below (TD case, XU is almost identical):

java.lang.NullPointerException: 

    at net.gtn.dimensionalpocket.common.core.pocket.Pocket.getBlockWorld(Pocket.java:343)
    at net.gtn.dimensionalpocket.common.tileentity.TileDimensionalPocketWallConnector.getDimPocketNeighbourTileEntity(TileDimensionalPocketWallConnector.java:124)
    at net.gtn.dimensionalpocket.common.tileentity.TileDimensionalPocketWallConnector.getInventoryOnOutsideWall(TileDimensionalPocketWallConnector.java:273)
    at net.gtn.dimensionalpocket.common.tileentity.TileDimensionalPocketWallConnector.func_94128_d(TileDimensionalPocketWallConnector.java:373)
    at cofh.thermaldynamics.duct.item.TileItemDuct.isSignificantTile(TileItemDuct.java:166)
    at cofh.thermaldynamics.block.TileTDBase.handleSideUpdate(TileTDBase.java:394)
    at cofh.thermaldynamics.block.TileTDBase.onNeighborBlockChange(TileTDBase.java:324)
    at cofh.core.block.BlockCoFHBase.func_149689_a(BlockCoFHBase.java:169)
    at cofh.thermaldynamics.duct.BlockDuct.func_149689_a(BlockDuct.java:254)
    at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:213)
    at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by NPException42** [comment]
This is a bad problem I hoped no one would encounter before the next version. If I recall that correctly, that problem is already fixed in the current dev build. Maybe @Jezza can throw out a fixed build. Depends if/how broken the code is atm.

**Comment by NPException42** [comment]
Oh btw: this is a problem we can/do work around, but is due to ExU and TD calling inventory methods on the client side.

**Comment by tali713** [comment]
Well, I'll be looking forward to that.  Glad to hear you can work around the issue.

**Comment by Jezza** [comment]
Haha, @NPException42 I don't know why you think the code is broken, the only thing that was ever broken was the item renderer, and I fixed that a week ago. :P

As for the issue, I'm pretty sure it's been fixed, I'll see about pushing out a quick fix.
